npm i bcrypt-nodejs - ENCRIPTAR CONTRASEYA
npm i body-parser - SIRVE PARA OBTNER INFORMACION DE UNA PETICION POST Y RETRONAR INFO EN JSON
npm i connect-multiparty - GUARDAR RECURSOS VIDEOS IMAGENES
npm i express
npm i moment - MANEJADOR DE FECHAS [TOKENS] FECHA DE EXPERIACION Y CREACION
npm i mongoose - MODELADO DE MONGODB BACKED
npm i jsonwebtoken - GENERAR UN TOKEN CON LA INFORMACION DE UN USUARIO
npm i jwt-simple- DECODIFICAR LOS TOKENS Y VERIFICAR SI ES VALIDO
npm install --save-dev nodemon - TRABAJAR EN MODO DESARROLLO - NO MODO PRODUCCION